import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing/navbar/Navbar";
import Sidebar from "@/components/landing/sidebar/Sidebar";
import GradualBlurContainer from "@/components/providers/GradualBlurContainer";
import FadeContent from "@/components/ReactBits/FadeContent";
import SmoothScrollProvider from "@/components/providers/SmoothScrollProvider";

const bricolagueFont = Bricolage_Grotesque({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bricolagueFont.className} antialiased bg-black`}>
        <SmoothScrollProvider>
          <main className="relative min-h-screen bg-black font-normal">
            <Navbar />
            <FadeContent blur={true} className="bg-black" duration={1000} delay={500} easing="power2.out" initialOpacity={0}>
              <Sidebar />
              {children}
            </FadeContent>
          </main>
          <GradualBlurContainer
            target="page"
            position="bottom"
            height="7rem"
            strength={2}
            divCount={5}
            curve="bezier"
            exponential
            opacity={1}
          />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}


